version: '3.3'

services:
  api:
    container_name: cc-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - backend
    ports:
      - '8080:8080'
    depends_on:
      - db
      - cache

  db:
    container_name: cc-postgres
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    networks:
      - backend
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

networks:
  backend:
