version: '3.3'

services:
  api:
    container_name: ec-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - backend
    ports:
      - '8080:8080'
    depends_on:
      - db
      - cache

  db:
    container_name: ec-postgres
    image: postgres:14
    restart: always
    networks:
      - backend
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

#  cache:
#    container_name: ec-redis
#    image: redis
#    restart: always
#    networks:
#      - backend
#    ports:
#      - '6379:6379'

networks:
  backend:
